name: globe_ai
description: A starting point for Dart libraries or applications.
version: 1.0.0
resolution: workspace

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  globe_runtime:

dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.0
