name: globe_ai
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.5.3

dependencies:
  globe_runtime: ^1.0.0
  path: ^1.9.1

dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.0
