use std::env;
use std::fs;
use std::path::Path;
use std::path::PathBuf;

fn main() {
    let project_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let include_path = PathBuf::from(format!("{}/third_party/dart/include", project_dir));
    let dart_binding_file = PathBuf::from(format!("{}/src/dart_api.rs", project_dir));

    let mut build = cc::Build::new();
    build
        .file("third_party/dart/include/dart_api_dl.c")
        .include(&include_path);

    if cfg!(target_os = "windows") {
        println!("cargo:rustc-link-arg=/FORCE:UNRESOLVED");
    } else {
        build.flag("-std=c11").flag("-fPIC");
        // Allow undefined symbols on Unix
        println!("cargo:rustc-link-arg=-Wl,-undefined,dynamic_lookup");
    }

    build.compile("dart_api_dl");

    println!("cargo:rerun-if-changed=third_party/dart/internal/dart_api_dl.c");
    println!("cargo:rerun-if-changed=third_party/dart/include/dart_api.h");
    println!("cargo:rerun-if-changed=Cargo.toml");

    // Generate Rust bindings for the Dart API
    let bindings = bindgen::Builder::default()
        .prepend_enum_name(false)
        .header("third_party/dart/include/dart_api_dl.h")
        .clang_arg("-Ithird_party/dart/include")
        .raw_line("// Automatically generated by bindgen. Do not edit.")
        .raw_line("#![allow(non_snake_case)]")
        .raw_line("#![allow(non_camel_case_types)]")
        .raw_line("#![allow(non_upper_case_globals)]")
        .raw_line("#![allow(unused)]")
        .generate()
        .expect("Unable to generate bindings");

    // Write the bindings to the custom directory
    bindings
        .write_to_file(dart_binding_file)
        .expect("Couldn't write bindings!");

    let version = env::var("CARGO_PKG_VERSION").unwrap();
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("version.rs");
    fs::write(
        &dest_path,
        format!("pub const VERSION: &str = \"{}\";", version),
    )
    .expect("Could not write version file");
}
