[package]
name = "dart_v8_runtime"
version = "0.1.0"
edition = "2021"

[lib]
name = "dartv8"
crate-type = ["cdylib"]

[dependencies]
libc = "0.2.169"
# deno_fetch = "=0.211.0"
# deno_permissions = "0.46.0"

reqwest = { version = "0.12.12", features = ["json"] }
rusty_v8 = "0.32.1"
tokio = { version = "^1.43.0", features = ["full"] }

[build-dependencies]
bindgen = "0.65"
cc = "1.0"
