[package]
name = "dart_v8_runtime"
version = "0.1.0"
edition = "2021"


[lib]
name = "_dartv8"
crate-type = ["cdylib"]

[[bin]]
name = "main"
test = false
bench = false

[dependencies]
dart-sys = "4.1.5"
reqwest = { version = "0.12.12", features = ["json"] }
rusty_v8 = "0.32.1"
tokio = { version = "^1.43.0", features = ["full"] }
tokio-macros = { version = "0.2.0-alpha.6" }
