name: globe_runtime
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.5.0

dev_dependencies:
  test: ^1.24.0
  
dependencies:
  ffi: ^2.1.3
  msgpack_dart: ^1.0.1
  path: ^1.9.1
