name: globe_runtime
description: A minimalist runtime designed to leverage the JavaScript ecosystem and its tools to accelerate development in Dart.
version: 1.0.5
repository: https://github.com/invertase/globe_runtime

environment:
  sdk: ^3.4.0

dev_dependencies:
  test: ^1.24.0
  lints: ^5.1.1
  version: ^3.0.2

dependencies:
  ffi: ^2.1.3
  path: ^1.9.1
  http: ^1.3.0
  protobuf: ^3.1.0
  msgpack_dart: ^1.0.1
