name: globe_runtime
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.5.3

dev_dependencies:
  test: ^1.24.0
  lints: ^5.1.1

dependencies:
  ffi: ^2.1.3
  path: ^1.9.1
  http: ^1.3.0
  msgpack_dart: ^1.0.1
