name: pretty_node
version: 1.0.0
description: A Dart package that uses Node.js modules.

environment:
  sdk: ^3.4.0

dependencies:
  globe_runtime: ^1.0.7
 

dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.0
  rps: ^0.7.0

scripts:
  build: npx tsup