name: Test Globe Runtime

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1

      - name: Add Globe Runtime shared library
        run: |
          sudo apt-get update && sudo apt-get install -y jq curl
          mkdir /.globe/runtime && cd /.globe/runtime
          curl -s https://api.github.com/repos/invertase/globe_runtime/releases/latest \
            | jq -r '.assets[] | select(.name == "libglobe_runtime-x86_64-unknown-linux-gnu.so") | .browser_download_url' \
            | xargs curl -L -OJ

      - name: Run tests
        working-directory: packages/globe_runtime
        run: dart test --reporter expanded --concurrency=1